services:
  - type: web
    name: prison-management-system
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: dbms_prison
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PHP_DISPLAY_ERRORS
        value: 1
      - key: PHP_ERROR_REPORTING
        value: E_ALL
    healthCheckPath: /index.php
    autoDeploy: true
    disk:
      name: storage
      mountPath: /storage
      sizeGB: 1 