services:
  - type: web
    name: prison-management-system
    env: node
    buildCommand: |
      apt-get update -y
      apt-get install -y software-properties-common apache2
      add-apt-repository -y ppa:ondrej/php
      apt-get update -y
      apt-get install -y php8.1 php8.1-cli php8.1-mysql php8.1-mbstring php8.1-xml php8.1-curl php8.1-json php8.1-zip php8.1-gd php8.1-pdo php8.1-pdo-mysql php8.1-session libapache2-mod-php8.1
      a2enmod php8.1
      a2enmod rewrite
      cp apache.conf /etc/apache2/sites-available/000-default.conf
      php -v
      yarn install
    startCommand: |
      apache2ctl -D FOREGROUND
    envVars:
      - key: DB_HOST
        value: yamabiko.proxy.rlwy.net
      - key: DB_PORT
        value: 30661
      - key: DB_USER
        value: root
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: railway
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PHP_DISPLAY_ERRORS
        value: 0
      - key: PHP_ERROR_REPORTING
        value: E_ALL & ~E_DEPRECATED & ~E_STRICT
    healthCheckPath: /index.php
    autoDeploy: true
    disk:
      name: storage
      mountPath: /storage
      sizeGB: 1 